// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  // Annict Oauth
  ANNICT_CLIENT_ID: string;
  ANNICT_CLIENT_SECRET: string;

  // Better Auth
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
}
