import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { NuqsAdapter } from 'nuqs/adapters/next'
import type { ReactNode } from 'react'
import { Toaster } from 'sonner'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="ja">
    <body className="antialiased">
      <SessionProvider>
        <NuqsAdapter>
          <>
            {children}
            <Toaster />
          </>
        </NuqsAdapter>
      </SessionProvider>
    </body>
  </html>
)

export default RootLayout
