import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="ja">
    <body className="antialiased">{children}</body>
  </html>
)

export default RootLayout
