import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { NuqsAdapter } from 'nuqs/adapters/next'
import type { ReactNode } from 'react'
import { Toaster } from 'sonner'
import { twJoin } from 'tailwind-merge'
import '../styles/globals.css'
import { Footer } from './_layouts/footer'
import { Header } from './_layouts/header'
import { SideMenu } from './_layouts/side-menu'
import styles from './layout.module.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="ja">
    <body>
      <SessionProvider>
        <NuqsAdapter>
          <div className={styles.layout}>
            <Header className={styles.header} />
            <SideMenu className={styles.sideMenu} />
            <main
              className={twJoin(styles.main, 'mx-auto w-full min-w-[56svw] max-w-[600px] py-4')}
            >
              {children}
            </main>
            <Footer className={styles.footer} />
          </div>
          <Toaster />
        </NuqsAdapter>
      </SessionProvider>
    </body>
  </html>
)

export default RootLayout
